import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'ncnn_yolo_options.freezed.dart';

final labelsDeaf = [
  "cảm ơn",
  "hẹn gặp lại",
  "khỏe",
  "không thích",
  "rất vui được gặp bạn",
  "sợ",
  "tạm biệt",
  "thích",
  "xin chào",
  "xin lỗi",
  "biết",
  "anh trai",
  "chị gái",
  "hiểu",
  "mẹ",
  "nhà",
  "nhớ",
  "tò mò",
  "yêu",
  "tức giận",
  "ghê tởm",
  "sợ hãi",
  "vui vẻ",
  "buồn",
  "bất ngờ",
  "tự nhiên",
  "khinh miệt"
];
final labels = [
  'người',
  'xe đạp',
  'xe hơi',
  'xe máy',
  'máy bay',
  'xe buýt',
  'xe lửa',
  'xe tải',
  'thuyền',
  'đèn giao thông',
  'vòi cứu hỏa',
  'biển báo dừng',
  'đồng hồ đỗ xe',
  'băng ghế',
  'chim',
  'con mèo',
  'chó',
  'ngựa',
  'con cừu',
  'bò',
  'con voi',
  'con gấu',
  'ngựa vằn',
  'hươu cao cổ',
  'balo',
  'Chiếc ô',
  'túi xách',
  'cà vạt',
  'va li',
  'đĩa bay',
  'ván trượt',
  'ván trượt tuyết',
  'quả bóng thể thao',
  'diều',
  'gậy bóng chày',
  'găng tay bóng chày',
  'ván trượt',
  'ván lướt sóng',
  'vợt tennis',
  'cái chai',
  'ly rượu',
  'cốc',
  'cái nĩa',
  'dao',
  'thìa',
  'cái bát',
  'chuối',
  'quả táo',
  'sandwich',
  'quả cam',
  'bông cải xanh',
  'củ cà rốt',
  'xúc xích',
  'pizza',
  'bánh rán',
  'bánh ngọt',
  'ghế',
  'đi văng',
  'cây trồng trong chậu',
  'giường',
  'bàn ăn',
  'nhà vệ sinh',
  'TV',
  'máy tính xách tay',
  'chuột',
  'xa',
  'bàn phím',
  'điện thoại di động',
  'lò vi sóng',
  'lò vi sóng',
  'máy nướng bánh mì',
  'bồn rửa',
  'tủ lạnh',
  'sách',
  'cái đồng hồ',
  'lọ cắm hoa',
  'kéo',
  'gấu bông',
  'máy sấy tóc',
  'bàn chải đánh răng',
  'cửa',
  'cầu thang',
  'cửa sổ',
  "100 nghìn",
  "10 nghìn",
  "1 nghìn",
  "200 nghìn",
  "20 nghìn",
  "2 nghìn",
  "500 nghìn",
  "50 nghìn",
  "5 nghìn"
];
