// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsIVJ9d1FBeiYPGE3EX2E4Eu-V7C8DPc0',
    appId: '1:1014607047105:android:153d8590fa64c0e262e740',
    messagingSenderId: '1014607047105',
    projectId: 'chatwithfirebase-19579',
    databaseURL: 'https://chatwithfirebase-19579-default-rtdb.firebaseio.com',
    storageBucket: 'chatwithfirebase-19579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ_8WFv8-zFjertnX3w1Ir50tWEgCnabU',
    appId: '1:1014607047105:ios:0529b13a7ee1733462e740',
    messagingSenderId: '1014607047105',
    projectId: 'chatwithfirebase-19579',
    databaseURL: 'https://chatwithfirebase-19579-default-rtdb.firebaseio.com',
    storageBucket: 'chatwithfirebase-19579.appspot.com',
    iosBundleId: 'com.nguoikhuyettat.nguoiKhuyetTat',
  );
}
