// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQFJThZ_NNHuuK--UYq-Tqq9B8J2OL2s',
    appId: '1:51589792579:android:ba60dcca7dae72045ba5f6',
    messagingSenderId: '51589792579',
    projectId: 'quanlyphuongtien-22dd4',
    databaseURL: 'https://quanlyphuongtien-22dd4-default-rtdb.firebaseio.com',
    storageBucket: 'quanlyphuongtien-22dd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUbZPy9fLegXrGdIktA-XvoMs_OhSOe0',
    appId: '1:51589792579:ios:2f6600a86a579a875ba5f6',
    messagingSenderId: '51589792579',
    projectId: 'quanlyphuongtien-22dd4',
    databaseURL: 'https://quanlyphuongtien-22dd4-default-rtdb.firebaseio.com',
    storageBucket: 'quanlyphuongtien-22dd4.appspot.com',
    iosBundleId: 'com.nguoikhuyettat.nguoiKhuyetTat',
  );

}